name: Build and Deploy NestJS to MonsterASP.NET

on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build NestJS app
        run: npm run build

      - name: Prepare deploy folder
        run: |
          mkdir publish
          Copy-Item dist -Destination publish/dist -Recurse
          Copy-Item package.json publish/
          Copy-Item package-lock.json publish/  # optional, if you use it
          Copy-Item .env publish/ -ErrorAction SilentlyContinue  # optional
          
      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: publish
